VERSION ?= 0.0.0-SNAPSHOT
CODESIGN_IDENTITY ?= Apple Development
EXPECTED_CODESIGN_AUTHORITY_PREFIX ?= Authority=Apple Development:
DEVELOPMENT_TEAM ?= W9C2P3N7Q2
NOTARIZE ?= 0
NOTARYTOOL_PROFILE ?= winmux
RELEASE_DIR ?= .release
RELEASE_TAG ?= v$(VERSION)
RELEASE_NOTES ?= auto
PUBLISH ?= 1
APP_INSTALL_DIR ?= /Applications
DEV_BUILD_CONFIGURATION ?= release
SPARKLE_PUBLIC_KEY ?= kcc3956V3+Yo8GtwFJ8Odb9sphIr09/9dsuoYBNtxf0=
ARGS ?=

.PHONY: dev-build dev-test dev-install dev-run generate xcodeproj build build-clean run run-clean cli check release install installed clean

generate:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let winMuxAppVersion = \"$(VERSION)\"" > Sources/Common/versionGenerated.swift && \
	git_hash="$$(git rev-parse HEAD 2>/dev/null || echo SNAPSHOT)"; \
	git_short_hash="$$(git rev-parse --short HEAD 2>/dev/null || echo SNAPSHOT)"; \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let gitHash = \"$$git_hash\"" "public let gitShortHash = \"$$git_short_hash\"" > Sources/Common/gitHashGenerated.swift'

xcodeproj:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	export XCODEGEN_WINMUX_VERSION="$(VERSION)" && \
	export XCODEGEN_WINMUX_CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" && \
	export XCODEGEN_WINMUX_DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" && \
	export XCODEGEN_WINMUX_SPARKLE_PUBLIC_KEY="$(SPARKLE_PUBLIC_KEY)" && \
	./script/install-dep.sh --xcodegen && \
	./.deps/xcodegen/xcodegen'

build:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	swift build && \
	swift build --target AppBundleTests && \
	rm -rf .debug && \
	mkdir .debug && \
	cp -r .build/debug/winmux .debug && \
	cp -r .build/debug/WinMuxApp .debug && \
	cp -R .build/debug/Sparkle.framework .debug/ && \
	for bundle in .build/debug/*.bundle; do [ ! -d "$$bundle" ] || cp -R "$$bundle" .debug/; done'

build-clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug'
	$(MAKE) build VERSION="$(VERSION)"

dev-build:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && source ./script/setup.sh && swift build -c "$(DEV_BUILD_CONFIGURATION)" -Xswiftc -DDEBUG'
	VERSION="$(VERSION)" DEV_BUILD_CONFIGURATION="$(DEV_BUILD_CONFIGURATION)" ./script/dev-app.sh build

dev-test:
	/bin/bash -lc 'cd "$(CURDIR)" && source ./script/setup.sh && swift test -c "$(DEV_BUILD_CONFIGURATION)" -Xswiftc -DDEBUG'

dev-install: dev-build
	./script/dev-app.sh install

dev-run:
	./script/dev-app.sh run $(ARGS)

run: dev-install
	./script/dev-app.sh run $(ARGS)

run-clean: build-clean run

cli:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && exec ./.debug/winmux $(ARGS)'

check:
	$(MAKE) dev-test DEV_BUILD_CONFIGURATION=debug
	$(MAKE) dev-test DEV_BUILD_CONFIGURATION=release
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	source ./script/setup.sh && \
	python3 -m unittest script/test_validate_appcast.py && \
	swift package resolve && \
	git diff --exit-code -- Package.resolved'

release:
	$(MAKE) xcodeproj VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	source ./script/setup.sh && \
	test -n "$(VERSION)" && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	archive_path="$$release_dir/$$app_name-$(VERSION).xcarchive"; \
	derived_data_path="$$release_dir/$$app_name-$(VERSION).deriveddata"; \
	app_path="$$archive_path/Products/Applications/$$app_name.app"; \
	zip_path="$$release_dir/$$app_name-$(VERSION).zip"; \
	appcast_path="$$release_dir/appcast.xml"; \
	log_path="$$release_dir/$$app_name-$(VERSION)-xcodebuild.log"; \
	rm -rf "$$archive_path" "$$zip_path" "$$appcast_path" "$$derived_data_path"; \
	mkdir -p "$$release_dir"; \
	xcodebuild-pretty "$$log_path" \
	    -project WinMux.xcodeproj \
	    -scheme WinMux \
	    -configuration Release \
	    -archivePath "$$archive_path" \
	    -derivedDataPath "$$derived_data_path" \
	    CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" \
	    DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" \
	    CODE_SIGN_STYLE=Automatic \
	    archive; \
	test -d "$$app_path"; \
	test "$$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$$app_path/Contents/Info.plist")" = "$(VERSION)"; \
	test "$$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$$app_path/Contents/Info.plist")" = "$(VERSION)"; \
	codesign --verify --deep --strict --verbose=2 "$$app_path"; \
	codesign -dv --verbose=4 "$$app_path" 2>&1 | grep -F "$(EXPECTED_CODESIGN_AUTHORITY_PREFIX)" >/dev/null; \
	ditto -c -k --sequesterRsrc --keepParent "$$app_path" "$$zip_path"; \
	sparkle_appcast="$$(find "$$derived_data_path/SourcePackages/artifacts" -type f -name generate_appcast -print -quit)"; \
	test -n "$$sparkle_appcast"; \
	appcast_stage="$$(mktemp -d "$$release_dir/appcast-stage.XXXXXX")"; \
	trap "rm -rf \"$$appcast_stage\"" EXIT; \
	cp "$$zip_path" "$$appcast_stage/"; \
	"$$sparkle_appcast" --download-url-prefix "https://github.com/ZimengXiong/winmux/releases/download/$(RELEASE_TAG)/" "$$appcast_stage"; \
	python3 script/validate-appcast.py "$$appcast_stage/appcast.xml" "$(VERSION)" "https://github.com/ZimengXiong/winmux/releases/download/$(RELEASE_TAG)/$$app_name-$(VERSION).zip"; \
	cp "$$appcast_stage/appcast.xml" "$$appcast_path"; \
	test -f "$$appcast_path"; \
	if [ "$(NOTARIZE)" = "1" ]; then \
	    test -n "$(NOTARYTOOL_PROFILE)"; \
	    xcrun notarytool submit "$$zip_path" --keychain-profile "$(NOTARYTOOL_PROFILE)" --wait; \
	    xcrun stapler staple "$$app_path"; \
	    xcrun stapler validate "$$app_path"; \
	    codesign --verify --deep --strict --verbose=2 "$$app_path"; \
	    spctl --assess --type execute --verbose=4 "$$app_path"; \
	    rm -f "$$zip_path"; \
	    ditto -c -k --sequesterRsrc --keepParent "$$app_path" "$$zip_path"; \
	else \
	    echo "Skipping notarization because NOTARIZE=$(NOTARIZE)"; \
	fi; \
	if [ "$(PUBLISH)" != "1" ]; then \
	    echo "Skipping GitHub release publish because PUBLISH=$(PUBLISH)"; \
	elif /usr/bin/which gh >/dev/null 2>&1; then \
	    if gh release view "$(RELEASE_TAG)" >/dev/null 2>&1; then \
	        gh release upload "$(RELEASE_TAG)" "$$zip_path" "$$appcast_path" --clobber; \
	    else \
	        if [ "$(RELEASE_NOTES)" = "auto" ]; then \
	            gh release create "$(RELEASE_TAG)" "$$zip_path" "$$appcast_path" --title "$$app_name $(VERSION)" --generate-notes; \
	        else \
	            gh release create "$(RELEASE_TAG)" "$$zip_path" "$$appcast_path" --title "$$app_name $(VERSION)" --notes "$(RELEASE_NOTES)"; \
	        fi; \
	    fi; \
	else \
	    echo "warning: gh is not installed; built $$zip_path but did not publish a GitHub release" >&2; \
	fi'

install:
	$(MAKE) release VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)" DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" PUBLISH=0
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	app_path="$$release_dir/$$app_name-$(VERSION).xcarchive/Products/Applications/$$app_name.app"; \
	install_dir="$(APP_INSTALL_DIR)"; \
	install_path="$$install_dir/$$app_name.app"; \
	test -d "$$app_path"; \
	mkdir -p "$$install_dir"; \
	osascript -e "tell application \"$$app_name\" to quit" >/dev/null 2>&1 || true; \
	rm -rf "$$install_path"; \
	ditto "$$app_path" "$$install_path"; \
	xattr -dr com.apple.quarantine "$$install_path" >/dev/null 2>&1 || true; \
	open "$$install_path"'

installed: install

clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug .deps .derived "$(RELEASE_DIR)" WinMux.xcodeproj'
